config/routes.rb
Rails.application.routes.draw do
# 管理者用# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
    get '/' => 'homes#top'
    resources :items,only: [:index,:create,:edit,:update,:show,:new]
    resources :genres,only: [:index,:create,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:edit,:update] do
     collection do
     resources :order_details, only: [:update,:show]
    end
    end
 end
# 顧客用# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  namespace :public do
   root to: 'homes#top'
   get "about" => "homes#about", as: "about"
   resources :customers,only: [:show,:edit,:update,]
   get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
   patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
   resources :addresses,only: [:index,:create,:edit,:update,:destroy]
   resources :items,only: [:index,:create,:update,:show,]
   resources :cart_items,only: [:index,:update,:destroy,:create] do
        delete 'destroy_all', to: 'cart_items#destroy_all'
   end
   resources :orders do
        collection do
        post 'confirm'
        get 'complete'
   end
   end
 end
end
  # devise_for :admins
  # devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :cart_items
  has_many :orders
  def active_for_authentication?
    super && (is_deleted == false)
  end
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	before_action :authenticate_admin!

  def index
  @customers = Customer.all.page(params[:page]).per(10)
  end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end
	end

	private

	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
	end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
</br><div class="container">
<div class="row">
  <div calss="col-xs-12">
    <%= render "layouts/error_messages", resource: @customer %>
    <h2 class="head-line title_h2 text-center bg-light">
      <%= @customer.decorate.full_name %>さんの会員情報編集
    </h2>
  <%= form_with model: @customer, url: admin_customer_path, local: true ,method: :patch do |f| %>
    <div class="col-xs-10">
      <div class="form-group col-xs-9">
        <%= f.label :"会員ID", class: "col-sm-4 control-label" %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"氏名", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name, class: "col-sm-3 form-control-static name" %>
        <%= f.text_field :first_name, class: "col-sm-3 form-control-static name" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"フリガナ", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name_kana, class: "col-sm-3 form-control-static name" %>
        <%= f.text_field :first_name_kana, class: "col-sm-3 form-control-static name" %>
      </div>
        <div class="form-group col-xs-9">
        <%= f.label :"郵便番号", autofocus: true, class: "col-sm-4 control-label" %>
        <%= f.text_field :postal_code, class: "col-sm-4 form-control-static postal_code" %>
        </div>
        <div class="form-group col-xs-9">
        <%= f.label :"住所", class: "col-sm-4 control-label" %>
        <%= f.text_field :address, class: "col-sm-6 form-control-static address"  %>
        </div>
        <div class="form-group col-xs-9">
        <%= f.label :"電話番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :telephone_number, class: "col-sm-4 form-control-static" %>
        </div>
        <div class="form-group col-xs-9">
        <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
        <%= f.text_field :email, class: "col-sm-6 form-control-static"%>
        </div>
      <div class="form-group col-xs-9">
        <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
        　<%= f.radio_button :is_deleted, false %>
        　<%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
        　<%= f.radio_button :is_deleted, true %>
        　<%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
      </div>
    </div>
      <div class="actions  col-xs-9 col-xs-offset-4">
        <%= f.submit '変更を保存' ,class: "btn btn-success" %>
      </div>
  <% end %>
    <div class="col-xs-12">
    </div>
  </div>
</div>
</div>

app/views/admin/customers/index.html.erb
</br><div class="container">
<div class="row">
  <div class="col-xs-10 col-xs-offset-1"><h2 class="head-line title_h2 text-left"><span class="bg-light" >会員一覧</span></h2>
    <table class="table table-hover table-bordered table-condensed ">
      <thead>
        <tr class="info bg-light">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td class="info col-xs-1 ">
              <%= customer.id %>
            </td>
            <td class="text-left">
              <%= link_to admin_customer_path(customer), class: "btn-link"  do %>
                <u><%= customer.decorate.full_name %></u>
              <% end %>
            </td>
            <td class="text-left">
              <%= customer.email %>
            </td>
            <td class="col-xs-2">
              <% if customer.is_deleted == true%>
                <p><i class="text-secondary">退会</i></p>
              <% else %>
                <p><i class="text-success">有効</i></p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link text-light" do %><i class="fas fa-sign-out-alt"></i> Log out<% end %>
    <div class= "text-center"><%= paginate(@customers) %></div>
</div>
</div>

app/views/admin/customers/show.html.erb
</br><div class="container">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="head-line title_h2 text-center bg-light">
      <%= @customer.decorate.full_name %>さんの会員詳細
      </h2>
      <div class="field">
        <p>会員ID&emsp;<%= @customer.id %></p>
      </div>
      <div class="field">
        <p>氏名&emsp;<%= @customer.decorate.full_name %></p>
      </div>
      <div class="field">
        <p>フリガナ&emsp;<%= @customer.decorate.kana_full_name %></p>
      </div>
      <div class="field">
        <p>郵便番号&emsp;<%= @customer.postal_code %></p>
      </div>
      <div class="field">
        <p>住所&emsp;<%= @customer.address %></p>
      </div>
      <div class="field">
        <p>電話番号&emsp;<%= @customer.telephone_number %></p>
      </div>
      <div class="field">
        <p>メールアドレス&emsp;<%= @customer.email%></p>
      </div>
      <div class="field">
        <p>
          会員ステータス&emsp;
          <% if @customer.is_deleted == true %>
            <span>　<i class="text-secondary">退会</i>
          <% elsif @customer.is_deleted == false %>
            　<i class="text-success">有効</i></span>
          <% end %>
        </p>
      </div>
      <div class="actions">
        <%= link_to "編集する",edit_admin_customer_path(@customer), class: "glyphicon glyphicon-pencil btn btn-success edit_shipping_addres_#{@customer.id}" %>
        <%= link_to " 注文履歴一覧を見る", admin_order_detail_path(@customer), class: "btn btn-info glyphicon glyphicon-folder-open" %>
      </div>
    </div>
  </div>
</div>