config/routes.rb
Rails.application.routes.draw do
# 管理者用# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
    get '/' => 'homes#top'
    resources :items,only: [:index,:create,:edit,:update,:show,:new]
    resources :genres,only: [:index,:create,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:index,:show,:edit,:update] do
     collection do
     resources :order_details, only: [:update,:show]
    end
    end
 end
# 顧客用# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  namespace :public do
   root to: 'homes#top'
   get "about" => "homes#about", as: "about"
   resources :customers,only: [:show,:edit,:update,]
   get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
   patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
   resources :addresses,only: [:index,:create,:edit,:update,:destroy]
   resources :items,only: [:index,:create,:update,:show,]
   resources :cart_items,only: [:index,:update,:destroy,:create] do
        delete 'destroy_all', to: 'cart_items#destroy_all'
   end
   resources :orders do
        collection do
        post 'confirm'
        get 'complete'
   end
   end
 end
end
  # devise_for :admins
  # devise_for :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :image
  def sum_of_price
    item.taxin_price * amount
  end
  def sum_price
    item.tax_price * amount
  end
  def sub_price(sub)
    (taxf_price(sub.item.tax_out_price) * sub.amount)
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :cart_items
  has_many :orders
  def active_for_authentication?
    super && (is_deleted == false)
  end
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/home.rb
class Home < ApplicationRecord

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  has_one_attached :image
  def taxin_price
        (price*1.1).round
  end
  def tax_price
        (price*1.0).round
  end
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  def sum_order_items
    self.order_details.all.sum(:amount)
  end

  def cart_items_price
   (item.price*1.1) * amount
  end

  def unfair
    total_amount - shipping_cost
  end

  enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item

    def sum_order_items
    self.order_details.all.sum(:total_amount)
    end

    enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_genres, only: [:new, :edit, :index, :create, :update]
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "新商品を登録しました"
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品内容をを変更しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction,
       :genre_id, :price, :is_active)
  end

  def set_genres
    @genres = Genre.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected
    # ログイン時のパスを変更してる
    def after_sign_in_path_for(resource)
      if customer_signed_in?
        public_root_path
      else
         admin_path
      end
    end

    #ログアウト時のパスの変更
    def after_sign_out_path_for(resource)
      public_root_path
    end

    # 新規登録の保存機能
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
  			 keys: [:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,])

      #sign_upの際にnameのデータ操作を許。追加したカラム。
  		devise_parameter_sanitizer.permit(:sign_in, keys: [:email])

    end

  private

  # before_action作成

  def set_item
    @item = Item.find(params[:id])
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
#   def current_cart
#     @cart_items = current_customer.cart_items
#   end

#   # 小数点切り捨てはfloor,３桁区切りはto_s(:delimited)
#   # 税込の計算
#   def tax_price(price)
#     (price * 1.1).floor
#   end

#   # 小計の計算
#   def sub_price(sub)
#     (tax_price(sub.product.tax_out_price) * sub.quantity)
#   end

#   # 合計金額の計算
#   def total_price(totals)
#     price = 0
#     totals.each do |total|
#       price  +=  sub_price(total)
#     end
#     return price
#   end

#   # 請求額の計算
#   def billing(order)
#     total_price(current_cart) + order.posta
#   end

#   def full_title(title = "")
#     base_title = "NaganoCAKE"
# 		if admin_signed_in?
# 			base_title + "|" + "(管理者) #{title}"
# 		else
# 			base_title + "|" + "#{title}"
# 		end
#   end

# 	def full_name(customer)
# 		customer.last_name + customer.first_name
# 	end

# 	def kana_full_name(customer)
# 		customer.kana_last_name+customer.kana_first_name
# 	end

#   def full_address(key)
# 		  "#{key.postal_code} #{key.address}"
#   end

end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yomogi&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">

        <div class="container">
          <a class="Logo navbar-brand p-3 " href="/">
            <%= link_to @public_path, class:"header-title " do %>
             <div>ながのCAKE</div>
            <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav lists-right">
              <% if customer_signed_in? %>

                <li class= "nav-item">
                 <button class="btn btn-default"> <%= link_to "マイページ", public_customer_path(current_customer), class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "商品一覧", public_items_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "カート", public_cart_items_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class="nav-item">
                  <button class="btn btn-default"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

              <% elsif admin_signed_in? %>
                <li class= items>
                  <button class="btn btn-default"><%= link_to '商品一覧', admin_items_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class= customers>
                  <button class="btn btn-default"><%= link_to '会員一覧', admin_customers_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class=orders>
                  <button class="btn btn-default"><%= link_to '注文履歴一覧', admin_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class=genres>
                  <button class="btn btn-default"><%= link_to 'ジャンル一覧', admin_genres_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class=logout>
                  <button class="btn btn-default"><%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

              <% else %>
                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "About", public_about_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                 <li class= "nav-item">
                   <button class="btn btn-default"><%= link_to "商品一覧", public_items_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "新規登録", new_customer_registration_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>

                <li class= "nav-item">
                 <button class="btn btn-default"><%= link_to "ログイン", new_customer_session_path, class: "link glyphicon glyphicon-pencil btn btn-default pull-right" %></button>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto" style="font-family: 'Kiwi Maru', serif;">
    <%= notice %>
    <%= yield %>
    </main>

  </body>


</html>